

' VLM  Arrays - Start
' Arrays per baked part
Dim BP_Cab: BP_Cab=Array(BM_Cab)
Dim BP_LEMK: BP_LEMK=Array(BM_LEMK)
Dim BP_LSling1: BP_LSling1=Array(BM_LSling1)
Dim BP_LSling2: BP_LSling2=Array(BM_LSling2)
Dim BP_Layer2: BP_Layer2=Array(BM_Layer2)
Dim BP_PF: BP_PF=Array(BM_PF)
Dim BP_Parts: BP_Parts=Array(BM_Parts)
Dim BP_REMK: BP_REMK=Array(BM_REMK)
Dim BP_RSling1: BP_RSling1=Array(BM_RSling1)
Dim BP_RSling2: BP_RSling2=Array(BM_RSling2)
Dim BP_Ramp1: BP_Ramp1=Array(BM_Ramp1)
Dim BP_Scoop: BP_Scoop=Array(BM_Scoop)
Dim BP_UnderPF: BP_UnderPF=Array(BM_UnderPF)
Dim BP_pantherLid: BP_pantherLid=Array(BM_pantherLid)
Dim BP_pantherLid2: BP_pantherLid2=Array(BM_pantherLid2)
Dim BP_pantherSupport: BP_pantherSupport=Array(BM_pantherSupport)
Dim BP_pantherSupport2: BP_pantherSupport2=Array(BM_pantherSupport2)
Dim BP_sw01: BP_sw01=Array(BM_sw01)
Dim BP_sw02: BP_sw02=Array(BM_sw02)
Dim BP_sw04: BP_sw04=Array(BM_sw04)
Dim BP_sw05: BP_sw05=Array(BM_sw05)
Dim BP_sw06: BP_sw06=Array(BM_sw06)
Dim BP_sw08: BP_sw08=Array(BM_sw08)
Dim BP_sw09: BP_sw09=Array(BM_sw09)
Dim BP_sw10: BP_sw10=Array(BM_sw10)
Dim BP_sw11: BP_sw11=Array(BM_sw11)
Dim BP_sw12: BP_sw12=Array(BM_sw12)
Dim BP_sw13: BP_sw13=Array(BM_sw13)
Dim BP_sw15: BP_sw15=Array(BM_sw15)
Dim BP_sw16: BP_sw16=Array(BM_sw16)
Dim BP_sw17: BP_sw17=Array(BM_sw17)
Dim BP_targetbank: BP_targetbank=Array(BM_targetbank)
' Arrays per lighting scenario
Dim BL_World: BL_World=Array(BM_Cab, BM_LEMK, BM_LSling1, BM_LSling2, BM_Layer2, BM_PF, BM_Parts, BM_REMK, BM_RSling1, BM_RSling2, BM_Ramp1, BM_Scoop, BM_UnderPF, BM_pantherLid, BM_pantherLid2, BM_pantherSupport, BM_pantherSupport2, BM_sw01, BM_sw02, BM_sw04, BM_sw05, BM_sw06, BM_sw08, BM_sw09, BM_sw10, BM_sw11, BM_sw12, BM_sw13, BM_sw15, BM_sw16, BM_sw17, BM_targetbank)
' Global arrays
Dim BG_Bakemap: BG_Bakemap=Array(BM_Cab, BM_LEMK, BM_LSling1, BM_LSling2, BM_Layer2, BM_PF, BM_Parts, BM_REMK, BM_RSling1, BM_RSling2, BM_Ramp1, BM_Scoop, BM_UnderPF, BM_pantherLid, BM_pantherLid2, BM_pantherSupport, BM_pantherSupport2, BM_sw01, BM_sw02, BM_sw04, BM_sw05, BM_sw06, BM_sw08, BM_sw09, BM_sw10, BM_sw11, BM_sw12, BM_sw13, BM_sw15, BM_sw16, BM_sw17, BM_targetbank)
Dim BG_Lightmap: BG_Lightmap=Array()
Dim BG_All: BG_All=Array(BM_Cab, BM_LEMK, BM_LSling1, BM_LSling2, BM_Layer2, BM_PF, BM_Parts, BM_REMK, BM_RSling1, BM_RSling2, BM_Ramp1, BM_Scoop, BM_UnderPF, BM_pantherLid, BM_pantherLid2, BM_pantherSupport, BM_pantherSupport2, BM_sw01, BM_sw02, BM_sw04, BM_sw05, BM_sw06, BM_sw08, BM_sw09, BM_sw10, BM_sw11, BM_sw12, BM_sw13, BM_sw15, BM_sw16, BM_sw17, BM_targetbank)
' VLM  Arrays - End
