#config_version=5

hardware:
  platform: opp
  driverboards: gen2

bcp:
  connections:
    local_display:
      port: 5050
  debug: true

modes:
  - base
  - beasts

opp:
   ports: /dev/ttyACM0, /dev/ttyACM1

displays:
  window:
    width: 640
    height: 160

switches:
  s_left_flipper:
    number: 0-0-1
    tags: left_flipper
  s_right_flipper:
    number: 0-0-2
    tags: right_flipper
  s_trough1:
    number: 0-0-3
  s_trough2:
    number: 0-0-8
  s_trough3:
    number: 0-0-9
  s_trough4:
    number: 0-0-10
  s_trough5:
    number: 0-0-11
  s_trough6:
    number: 0-0-27
  s_trough_jam:
    number: 0-0-26
  s_plunger:
    number: 0-0-28
  s_start:
    number: 0-0-29
    tags: start
  s_cave_scoop:
    number: 0-0-30
  s_dt_map1:
    number: 0-0-31
  s_dt_map2:
    number: 0-0-32
  s_dt_map3:
    number: 0-0-33
  s_dt_map4:
    number: 0-0-34
  s_dt_map5:
    number: 0-0-35
  s_dt_map6:
    number: 0-0-36
  s_map1:
    number: 0-0-37
  s_map2:
    number: 0-0-38
  s_map3:
    number: 0-0-39
  s_map4:
    number: 0-0-40
  s_map5:
    number: 0-0-41
  s_map6:
    number: 0-0-42
  s_left_ramp_opto:
    number: 0-0-43

coils:
  c_flipper_left_main:
    number: 0-0-1
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: 0-0-2
    allow_enable: true
  c_flipper_right_main:
    number: 0-0-3
    default_pulse_ms: 20
  c_flipper_right_hold:
    number: 0-0-4
    allow_enable: true
  c_trough_eject:
    number: 0-0-5
    default_pulse_ms: 20
    debug: true
  c_plunger:
    number: 0-0-6
    default_pulse_ms: 20
  c_cave_scoop:
    number: 0-0-7
    default_pulse_ms: 20
  c_dt_reset:
    number: 0-0-8
    default_pulse_ms: 20
    debug: true
  c_dt_knockdown_1:
    number: 0-0-9
    default_pulse_ms: 20
  c_dt_knockdown_2:
    number: 0-0-10
    default_pulse_ms: 20
  c_dt_knockdown_3:
    number: 0-0-11
    default_pulse_ms: 20
  c_dt_knockdown_4:
    number: 0-0-12
    default_pulse_ms: 20
  c_dt_knockdown_5:
    number: 0-0-13
    default_pulse_ms: 20
  c_dt_knockdown_6:
    number: 0-0-14
    default_pulse_ms: 20
  c_panther_main:
    number: 0-0-15
    default_pulse_ms: 4
    default_hold_power: 0.2
  c_panther_hold:
    number: 0-0-16
    allow_enable: true

dual_wound_coils:
  c_panther_dualcoil:
    hold_coil: c_panther_hold
    main_coil: c_panther_main

diverters:
  panther_diverter:
    activate_events: activate_panther
    deactivate_events: deactivate_panther
    activation_coil: c_panther_dualcoil
    type: hold
    activation_time: 3s
    enable_events: ball_started
    disable_events: ball_ended

drop_targets:
  map1:
    switch: s_dt_map1
    reset_coil: c_dt_reset
    knockdown_coil: c_dt_knockdown_1
  map2:
    switch: s_dt_map2
    reset_coil: c_dt_reset
    knockdown_coil: c_dt_knockdown_2
  map3:
    switch: s_dt_map3
    reset_coil: c_dt_reset
    knockdown_coil: c_dt_knockdown_3
  map4:
    switch: s_dt_map4
    reset_coil: c_dt_reset
    knockdown_coil: c_dt_knockdown_4
  map5:
    switch: s_dt_map5
    reset_coil: c_dt_reset
    knockdown_coil: c_dt_knockdown_5
  map6:
    switch: s_dt_map6
    reset_coil: c_dt_reset
    knockdown_coil: c_dt_knockdown_6  

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper

keyboard:
  debug: yes
  shift+shift:
    switch: s_left_flipper
  shift+rshift:
    switch: s_right_flipper
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  5:
    switch: s_trough5
    toggle: true
  p:
    switch: s_plunger
    toggle: true
  s: 
    switch: s_start
  j: 
    switch: s_right_inlane

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    debug: true
  bd_plunger:
    ball_switches: s_plunger
    eject_coil: c_plunger
    mechanical_eject: true
    eject_targets: playfield
    eject_timeouts: 3s
  bd_cave_scoop:
    ball_switches: s_cave_scoop
    eject_coil: c_cave_scoop
    mechanical_eject: false
    eject_timeouts: 2s