#config_version=5

hardware:
  platform: opp
  driverboards: gen2

opp:
   ports: /dev/ttyACM0, /dev/ttyACM1

switches:
  s_left_flipper:
    number: 0-0-1
    tags: left_flipper
  s_right_flipper:
    number: 0-0-2
    tags: right_flipper
  s_trough1:
    number: 0-0-3
  s_trough2:
    number: 0-0-8
  s_trough3:
    number: 0-0-9
  s_trough4:
    number: 0-0-10
  s_trough5:
    number: 0-0-11
  s_trough6:
    number: 0-0-27
  s_trough_jam:
    number: 0-0-26

coils:
  c_flipper_left_main:
    number: 0-0-1
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: 0-0-2
    allow_enable: true
  c_flipper_right_main:
    number: 0-0-3
    default_pulse_ms: 20
  c_flipper_right_hold:
    number: 0-0-4
    allow_enable: true
  c_trough_eject:
    number: 0-0-5
    default_pulse_ms: 20

playfields:
  playfield:
    tags: default
    default_source_device: None

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3

displays:
  window:
    width: 800
    height: 600

slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 50
        color: red
      - type: rectangle
        width: 240
        height: 60
  attract_started:
    widgets:
      - text: ATTRACT MODE
        type: text

slide_player:
  init_done: welcome_slide
  mode_attract_started: attract_started

keyboard:
  debug: yes
  shift+shift:
    switch: s_left_flipper
  shift+rshift:
    switch: s_right_flipper