# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.version.outputs.build_number }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        run: |
          echo "build_number=$(git rev-list 1295e43d69488b1a9d128bde0edc14347097e1f1..HEAD --count)"  >> $GITHUB_OUTPUT

      - name: Download vpxtool
        run: |
          wget https://github.com/francisdb/vpxtool/releases/download/v0.10.1/vpxtool-Linux-x86_64-musl-v0.10.1.tar.gz
          tar -xzf vpxtool-Linux-x86_64-musl-v0.10.1.tar.gz
        
      - name: Run Command
        run: |
          git rev-list --max-parents=0 HEAD
          ./vpxtool assemble aztecquest
          mv ./aztecquest.vpx ./aztecquest${{steps.version.outputs.build_number}}.vpx
          
      - uses: actions/upload-artifact@v4
        with:
          name: AztecQuest_${{ steps.version.outputs.build_number }}
          path: ./aztecquest{{steps.version.outputs.build_number}}.vpx
